// JavaScript source code

// on each radio button click
	$('.radio_button_label').click(function(){
		// declare sum variable
		let sum;

	// if this radio button is in the Plastic_single_use group
	if($(this).prev().is('[name="Plastic_single_use"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Plastic_straws group
	else if($(this).prev().is('[name="Plastic_straws"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Plastic_cups group
	else if($(this).prev().is('[name="Plastic_cups"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Plastic_bottles group
	else if($(this).prev().is('[name="Plastic_bottles"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Plastic_cooler group
	else if($(this).prev().is('[name="Plastic_cooler"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Plastic_stirrers group
	else if($(this).prev().is('[name="Plastic_stirrers"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Recycling_program group
	else if($(this).prev().is('[name="Recycling_program"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Recycling_bins group
	else if($(this).prev().is('[name="Recycling_bins"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Waste_recycled group
	else if($(this).prev().is('[name="Waste_recycled"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	// if this radio button is in the Reuse_towels group
	else if($(this).prev().is('[name="Reuse_towels"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }


		// if this radio button is in the Daily_clean group
	else if($(this).prev().is('[name="Daily_clean"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	
		// if this radio button is in the Opt_out group
	else if($(this).prev().is('[name="Opt_out"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

    	// if this radio button is in the Toilets_water_efficient group
	else if($(this).prev().is('[name="Toilets_water_efficient"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }


        	// if this radio button is in the Shower_water_efficient group
	else if($(this).prev().is('[name="Shower_water_efficient"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }


         	// if this radio button is in the Locally_sourced_food group
	else if($(this).prev().is('[name="Locally_sourced_food"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

	
             	// if this radio button is in the Extend group
	else if($(this).prev().is('[name="Extend"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }

				// if this radio button is in the LED_bulbs group
	else if($(this).prev().is('[name="LED_bulbs"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
				// if this radio button is in the Electricity_controlled group
	else if($(this).prev().is('[name="Electricity_controlled"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
				// if this radio button is in the Reduce_food_waste group
	else if($(this).prev().is('[name="Reduce_food_waste"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
				
	else if($(this).prev().is('[name="Vegetarian_menu"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	
	else if($(this).prev().is('[name="Vegan_menu"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Organic_food"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Yes"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Local_staff"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Minimal_wage"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Social_benefits"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Invest_sustainability_projects"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Tours"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Provide_with_info"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Wild_animals"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Animals_kept_captive"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Green_spaces"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Pesticides"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Aware"]:checked').attr('add-value')) || 0)
		;
    }
	
	else if($(this).prev().is('[name="Aware"]')) {
		sum = Number($(this).prev().attr('add-value'))
		+ (Number($('input[name="Plastic_single_use"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_straws"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cups"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_bottles"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_cooler"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Plastic_stirrers"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_program"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Recycling_bins"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Waste_recycled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reuse_towels"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Daily_clean"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Opt_out"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Toilets_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Shower_water_efficient"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Locally_sourced_food"]:checked').attr('add-value')) || 0)
        + (Number($('input[name="Extend"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="LED_bulbs"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Electricity_controlled"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Reduce_food_waste"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegetarian_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Vegan_menu"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Organic_food"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Yes"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Local_staff"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Minimal_wage"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Social_benefits"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Invest_sustainability_projects"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Tours"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Provide_with_info"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Wild_animals"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Animals_kept_captive"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Green_spaces"]:checked').attr('add-value')) || 0)
		+ (Number($('input[name="Pesticides"]:checked').attr('add-value')) || 0)
		;
    }


	// display the sum
	// NB: use sum directly if not interested in formatting
	// $('.value').text(sum);
	$('.value').text(sum);
	// add the radio button's value to the hidden input field
	$('.score').val(sum);
  });
